a="kishore from erode"
print(len(a))
print(a[0])
print(a[3])
print(a[-1])
print(a.index("r"))
print(a.count("e"))
print(a.upper())
print(a.lower())
print(a.title())
print(a.startswith("kishore"))
print(a.endswith("kishore"))
print(a.replace("erode","chennai"))
print(a.split(" "))
a=a.strip()
print(a)
print(a.encode("utf-8"))
print(len(a))